name: can we compile?

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y json-c qt6-base qt6-multimedia
    - name: frontend
      run: make js
    - name: backend
      run: make b-install
    - name: rentnerend
      run: make r-install
